spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:file:~/data/anime
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        order_inserts: true
        show_sql: true
        jdbc:
          batch_size: 30
  sql:
    init:
      mode: always