INSERT INTO ANIME (EPISODES, NAME, STATUS)
VALUES (1000, 'DOAKDMOADOAKSMDOAMDOMSOKAMDOKAMDOAKSMds', 'obra prima');
--
-- INSERT INTO ANIME (EPISODES, NAME, STATUS)
-- VALUES (616, 'naruto SHIPPUDEN', 'obra prima');
